In [1]:
import re
import numpy as np
import pandas as pd

In [35]:

def encontraOpening(moves, openings):
    maiorOpening = 0
    openingName = ''
    for i in range(len(openings)):
        moveString = openings['pgn'][i]
        if moveString in moves and len(moveString)>maiorOpening:
            maiorOpening = len(moveString)
            openingName = openings['name'][i]

    return openingName

In [4]:
filename = 'games_db_1_3.csv'

players = pd.read_csv('games/'+filename)

players.head()

,id,ranked,time_control,status,winner,white,black,moves
0,db338032-0f2b-11df-8000-000000010001,True,blitz,resigned,michaelq2d5,michaelq2d5,malachi76,1. d4 d5 2. c4 c6 3. cxd5 cxd5 4. Nf3 Nf6 5. N...
1,38c7cc80-0f2c-11df-8000-000000010001,True,blitz,checkmated,malachi76,malachi76,michaelq2d5,1. e4 e5 2. Nf3 Nc6 3. Bc4 Bc5 4. O-O Nf6 5. c...
2,978d4682-0f2c-11df-8000-000000010001,True,blitz,resigned,michaelq2d5,Jojo_Dy,michaelq2d5,1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 4. Ba4 Nf6 5. O-...
3,ca373ea8-0f2c-11df-8000-000000010001,True,blitz,timeout,Surfsmurf,michaelq2d5,Surfsmurf,1. d4 d6 2. Nf3 Bg4 3. c4 c6 4. Nc3 Nd7 5. e4 ...
4,3e71e200-0f2d-11df-8000-000000010001,True,blitz,resigned,michaelq2d5,Adolf_Anderssen,michaelq2d5,1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 4. Ba4 Nf6 5. O-...

In [15]:
players['moves']

0        1. d4 d5 2. c4 c6 3. cxd5 cxd5 4. Nf3 Nf6 5. N...
1        1. e4 e5 2. Nf3 Nc6 3. Bc4 Bc5 4. O-O Nf6 5. c...
2        1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 4. Ba4 Nf6 5. O-...
3        1. d4 d6 2. Nf3 Bg4 3. c4 c6 4. Nc3 Nd7 5. e4 ...
4        1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 4. Ba4 Nf6 5. O-...
                               ...
36443    1. e3 e5 2. Bd3 Qf6 3. f4 Bc5 4. Qf3 exf4 5. e...
36444    1. e4 e5 2. Nf3 Bc5 3. c3 c6 4. d4 d5 5. dxc5 ...
36445                     1. Nf3 Nf6 2. d4 e5 3. c3 g6 0-1
36446    1. d4 e6 2. Nf3 Qf6 3. e4 c5 4. dxc5 Bxc5 5. B...
36447    1. d4 g6 2. Nf3 d5 3. Bf4 Nf6 4. e3 Bg7 5. h3 ...
Name: moves, Length: 36448, dtype: object

In [10]:
openings = pd.read_csv('../Openings/openings.csv')

openings.head(10)

,eco,name,pgn
0,A00,Amar Gambit,1. Nh3 d5 2. g3 e5 3. f4 Bxh3 4. Bxh3 exf4
1,A00,Amar Opening,1. Nh3
2,A00,Amar Opening: Gent Gambit,1. Nh3 d5 2. g3 e5 3. f4 Bxh3 4. Bxh3 exf4 5. ...
3,A00,Amar Opening: Paris Gambit,1. Nh3 d5 2. g3 e5 3. f4
4,A00,Amsterdam Attack,1. e3 e5 2. c4 d6 3. Nc3 Nc6 4. b3 Nf6
5,A00,Anderssen's Opening,1. a3
6,A00,Anderssen's Opening: Polish Gambit,1. a3 a5 2. b4
7,A00,Barnes Opening: Fool's Mate,1. f3 e5 2. g4 Qh4#
8,A00,Barnes Opening: Gedult Gambit,1. f3 d5 2. e4 g6 3. d4 dxe4 4. c3
9,A00,Barnes Opening: Gedult Gambit,1. f3 f5 2. e4 fxe4 3. Nc3

In [38]:
players['opening'] = players.apply(lambda x: encontraOpening(x['moves'], openings), axis=1)

players.head(10)

,id,ranked,time_control,status,winner,white,black,moves,opening
0,db338032-0f2b-11df-8000-000000010001,True,blitz,resigned,michaelq2d5,michaelq2d5,malachi76,1. d4 d5 2. c4 c6 3. cxd5 cxd5 4. Nf3 Nf6 5. N...,Slav Defense: Exchange Variation
1,38c7cc80-0f2c-11df-8000-000000010001,True,blitz,checkmated,malachi76,malachi76,michaelq2d5,1. e4 e5 2. Nf3 Nc6 3. Bc4 Bc5 4. O-O Nf6 5. c...,"Italian Game: Classical Variation, Albin Gambit"
2,978d4682-0f2c-11df-8000-000000010001,True,blitz,resigned,michaelq2d5,Jojo_Dy,michaelq2d5,1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 4. Ba4 Nf6 5. O-...,"Ruy Lopez: Closed, Worrall Attack, Castling Line"
3,ca373ea8-0f2c-11df-8000-000000010001,True,blitz,timeout,Surfsmurf,michaelq2d5,Surfsmurf,1. d4 d6 2. Nf3 Bg4 3. c4 c6 4. Nc3 Nd7 5. e4 ...,Wade Defense
4,3e71e200-0f2d-11df-8000-000000010001,True,blitz,resigned,michaelq2d5,Adolf_Anderssen,michaelq2d5,1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 4. Ba4 Nf6 5. O-...,"Ruy Lopez: Closed, Closed Defense"

In [40]:
players

,id,ranked,time_control,status,winner,white,black,moves,opening
0,db338032-0f2b-11df-8000-000000010001,True,blitz,resigned,michaelq2d5,michaelq2d5,malachi76,1. d4 d5 2. c4 c6 3. cxd5 cxd5 4. Nf3 Nf6 5. N...,Slav Defense: Exchange Variation
1,38c7cc80-0f2c-11df-8000-000000010001,True,blitz,checkmated,malachi76,malachi76,michaelq2d5,1. e4 e5 2. Nf3 Nc6 3. Bc4 Bc5 4. O-O Nf6 5. c...,"Italian Game: Classical Variation, Albin Gambit"
2,978d4682-0f2c-11df-8000-000000010001,True,blitz,resigned,michaelq2d5,Jojo_Dy,michaelq2d5,1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 4. Ba4 Nf6 5. O-...,"Ruy Lopez: Closed, Worrall Attack, Castling Line"
3,ca373ea8-0f2c-11df-8000-000000010001,True,blitz,timeout,Surfsmurf,michaelq2d5,Surfsmurf,1. d4 d6 2. Nf3 Bg4 3. c4 c6 4. Nc3 Nd7 5. e4 ...,Wade Defense
4,3e71e200-0f2d-11df-8000-000000010001,True,blitz,resigned,michaelq2d5,Adolf_Anderssen,michaelq2d5,1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 4. Ba4 Nf6 5. O-...,"Ruy Lopez: Closed, Closed Defense"
...,...,...,...,...,...,...,...,...,...
36443,52dfcc80-aa6b-11e6-8000-000000010001,True,bullet,resigned,SaudiSalman,SaudiSalman,G2_Coder,1. e3 e5 2. Bd3 Qf6 3. f4 Bc5 4. Qf3 exf4 5. e...,Van't Kruijs Opening
36444,a5b9843c-aa6b-11e6-8000-000000010001,True,bullet,checkmated,G2_Coder,ricfazolim,G2_Coder,1. e4 e5 2. Nf3 Bc5 3. c3 c6 4. d4 d5 5. dxc5 ...,King's Pawn Game: Busch-Gass Gambit
36445,2037e1f8-ab08-11e6-8000-000000010001,True,blitz,abandoned,G2_Coder,Vin_it007,G2_Coder,1. Nf3 Nf6 2. d4 e5 3. c3 g6 0-1,Zukertort Opening
36446,08fdf1a8-ab12-11e6-8000-000000010001,True,blitz,checkmated,G2_Coder,G2_Coder,10101987,1. d4 e6 2. Nf3 Qf6 3. e4 c5 4. dxc5 Bxc5 5. B...,Horwitz Defense
36447,3fc52c28-ac26-11e6-8000-000000010001,True,blitz,checkmated,G2_Coder,G2_Coder,cristiano1972,1. d4 g6 2. Nf3 d5 3. Bf4 Nf6 4. e3 Bg7 5. h3 ...,Modern Defense

In [42]:
players['moves'][36447]

'1. d4 g6 2. Nf3 d5 3. Bf4 Nf6 4. e3 Bg7 5. h3 O-O 6. c3 Nc6 7. Bd3 Bf5 8. Bxf5 gxf5 9. O-O e6 10. Nbd2 Re8 11. Rb1 Ne4 12. g4 fxg4 13. hxg4 f5 14. gxf5 exf5 15. c4 Ne7 16. cxd5 Ng6 17. Bh2 Qxd5 18. b3 Re6 19. Rc1 c6 20. Nxe4 Rxe4 21. Rc5 Rg4+ 22. Bg3 Qe4 23. Ne5 Nxe5 24. Rxe5 Bxe5 25. dxe5 Qxe5 26. Kh1 Rf8 27. Bxe5 Rh4+ 28. Bh2 f4 29. Rg1+ Kh8 30. Qd4+ Rf6 31. Qxf6# 1-0'

In [43]:
filename = 'games_db_1_3.csv'
players.to_csv('gamesWithOpenings/'+filename,index = False)

In [48]:
players['opening'].value_counts()

Sicilian Defense: Closed                                        961
Queen's Pawn Game                                               625
Caro-Kann Defense                                               575
Zukertort Opening                                               571
Modern Defense                                                  568
                                                               ...
French Defense: Tarrasch Variation, Modern System                 1
Nimzo-Indian Defense: Sämisch Variation, Botvinnik Variation      1
Ruy Lopez: Berlin Defense, Beverwijk Variation                    1
Bird Opening: From's Gambit, Lasker Variation                     1
Bogo-Indian Defense: Vitolins Variation                           1
Name: opening, Length: 1093, dtype: int64

In [50]:
players[players['opening'] == 'Bogo-Indian Defense: Vitolins Variation']

,id,ranked,time_control,status,winner,white,black,moves,opening
13890,88181900-45a1-11e5-8000-000000010001,True,bullet,resigned,michaelq2d5,michaelq2d5,German_Bazeev,1. d4 Nf6 2. c4 e6 3. Nf3 Bb4+ 4. Bd2 c5 5. Bx...,Bogo-Indian Defense: Vitolins Variation